<h3 style="color:blue;">Team 9 : DDR Assignment 4 </h3>
<h4>Japsowin Kaur | Shalini Mishra | Shivani Sharma

## Part 1
<h5>(a) Go to http://www.omdbapi.com/ and make yourself familiar with the API and its use. Request an API Key from the page. Specifically, read "Usage", "Parameters", and "Examples", and write down the URL string that would search for all the movies containing the word "blade". Include it as a comment in your code script.</h5>
<h4>Answer:</h4>
http://omdbapi.com/?s=blade*&apikey=ce1b31ce&type=movie<br>
<b>s</b> for movie title to search for<br>
since, we needed any movie title that have 'Blade' in its name. We searched for <b>blade*</b><br>
We need to search for movies so we set the <b>type</b> to <b>movie</b><br>

<h5>(b) Write a program in Python or Java that executes the above API call and prints the result to the screen. You can use the parameters "Plot: Short" and "Response: JSON". (0.1 bonus points: make your code pretty-print the returned JSON. You may use a package to do so.)</h5>
<h4>Answer:</h4> PFB the code below

In [2]:
#importing necessary libraries
import requests as r

#Getting the results from page 1 as default is set as page=1(given in the website)
url='http://omdbapi.com/?s=blade*&apikey=ce1b31ce&type=movie'
response=r.get(url)
response.json()

{'Search': [{'Title': 'Blade Runner',
   'Year': '1982',
   'imdbID': 'tt0083658',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'},
  {'Title': 'Blade Runner 2049',
   'Year': '2017',
   'imdbID': 'tt1856101',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg'},
  {'Title': 'Blade',
   'Year': '1998',
   'imdbID': 'tt0120611',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg'},
  {'Title': 'Blade II',
   'Year': '2002',
   'imdbID': 'tt0187738',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BOWVjZTIzNDYtNTBlNC00NTJjLTkzOTEtOTE0MjlhYzI2YTcyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg'},
  {'Title': 'Blade: Trinity',
   'Year': '2004',
   'imdbID': 'tt0359013',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMjE0Nzg2MzI3MF5BMl5BanBnXkFtZTYwMjExODQ3._V1_SX300.jpg'},
  {'Title': 'Blades of Glory',
   'Year': '2007',
   'imdbID': 'tt0445934',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY3MDMyMTYxMl5BMl5BanBnXkFtZTcwMjk0NzI0MQ@@._V1_SX300.jpg'},
  {'Title': 'Sling Blade',
   'Year': '1996',
   'imdbID': 'tt0117666',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNGY5NWIxMjAtODBjNC00MmZhLTk1ZTAtNGRhYThlOTNjMTQwXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg'},
  {'Title': 'Dragon Blade',
   'Year': '2015',
   'imdbID': 'tt3672840',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk0MjgxOTQ5MF5BMl5BanBnXkFtZTgwODA3NTUwNjE@._V1_SX300.jpg'},
  {'Title': 'Blade of the Immortal',
   'Year': '2017',
   'imdbID': 'tt5084170',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BYzIwYmJlMjktMzJiMy00YmQzLThmNWYtNWY3NGViZjc4MzYwXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SX300.jpg'},
  {'Title': 'Shinobi: Heart Under Blade',
   'Year': '2005',
   'imdbID': 'tt0475723',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNjZhMTNmMTItNmU4Mi00YTdkLWFkZWUtOGExNTQ3MGRiYWYyXkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_SX300.jpg'}],
 'totalResults': '224',
 'Response': 'True'}

In [3]:
import pprint

pprint.pprint(response.json())

{'Response': 'True',
 'Search': [{'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
             'Title': 'Blade Runner',
             'Type': 'movie',
             'Year': '1982',
             'imdbID': 'tt0083658'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg',
             'Title': 'Blade Runner 2049',
             'Type': 'movie',
             'Year': '2017',
             'imdbID': 'tt1856101'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg',
             'Title': 'Blade',
             'Type': 'movie',
             'Year': '1998',
             'imdbID': 'tt0120611'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BOWVjZTIzNDYtNTBlNC00NTJjLTkzOTEtOTE0MjlhYzI2YTcyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
             'Title': 'Blade II',
             'Type': 'movie',
             'Year': '2002',
             'imdbID': 'tt0187738'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMjE0Nzg2MzI3MF5BMl5BanBnXkFtZTYwMjExODQ3._V1_SX300.jpg',
             'Title': 'Blade: Trinity',
             'Type': 'movie',
             'Year': '2004',
             'imdbID': 'tt0359013'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY3MDMyMTYxMl5BMl5BanBnXkFtZTcwMjk0NzI0MQ@@._V1_SX300.jpg',
             'Title': 'Blades of Glory',
             'Type': 'movie',
             'Year': '2007',
             'imdbID': 'tt0445934'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BNGY5NWIxMjAtODBjNC00MmZhLTk1ZTAtNGRhYThlOTNjMTQwXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg',
             'Title': 'Sling Blade',
             'Type': 'movie',
             'Year': '1996',
             'imdbID': 'tt0117666'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk0MjgxOTQ5MF5BMl5BanBnXkFtZTgwODA3NTUwNjE@._V1_SX300.jpg',
             'Title': 'Dragon Blade',
             'Type': 'movie',
             'Year': '2015',
             'imdbID': 'tt3672840'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BYzIwYmJlMjktMzJiMy00YmQzLThmNWYtNWY3NGViZjc4MzYwXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SX300.jpg',
             'Title': 'Blade of the Immortal',
             'Type': 'movie',
             'Year': '2017',
             'imdbID': 'tt5084170'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BNjZhMTNmMTItNmU4Mi00YTdkLWFkZWUtOGExNTQ3MGRiYWYyXkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_SX300.jpg',
             'Title': 'Shinobi: Heart Under Blade',
             'Type': 'movie',
             'Year': '2005',
             'imdbID': 'tt0475723'}],
 'totalResults': '224'}

<h5>(c) Parse the JSON string in (b) to an internal Python or Java object for further handling. Then write code that iterates through the search results and prints the imdbID results to the screen.</h5>

In [4]:
#getting an estimate of total results in integer format
#my_obj is a python dict object
my_obj=response.json()
#Getting total results to decide our loop range
total_res=int(my_obj['totalResults'])

In [6]:
import json as js

#Parse through all the result pages
#Assuming that each page has 10 results
for pg in range(1,int(total_res/10)):
    url='http://omdbapi.com/?s=blade*&page='+str(pg)+'&apikey=ce1b31ce&type=movie'
    response=r.get(url)
    #Deserialize a str or unicode instance containing a JSON document to a Python object
    result=js.loads(response.text)
    #Print IMDB Ids of all the movie titles
    for i in range(1,len(result['Search'])):
        #Look for imdbID in each 'Search'
            print((result['Search'][i]['imdbID']))

tt1856101
tt0120611
tt0187738
tt0359013
tt0445934
tt0117666
tt3672840
tt5084170
tt0475723
tt7428594
tt0442286
tt1648093
tt0083366
tt0086972
tt0310149
tt0112800
tt0085303
tt4019426
tt0108181
tt0159693
tt0076360
tt1587156
tt7055592
tt0066154
tt0961079
tt1730695
tt0075329
tt0222344
tt0096936
tt0056963
tt0488338
tt0089930
tt0108622
tt7445510
tt0104702
tt1467299
tt0078918
tt0281011
tt1663145
tt7656770
tt3512282
tt0291180
tt0098216
tt1809274
tt0080443
tt0181041
tt3012528
tt1679583
tt0256531
tt1582481
tt1415224
tt1865375
tt0154238
tt1726641
tt0107954
tt1753855
tt0060350
tt0047448
tt0202027
tt0164524
tt0344464
tt6789126
tt1988382
tt10086692
tt0398784
tt7879362
tt1846491
tt2033352
tt0952643
tt0944069
tt1864253
tt0225189
tt0094757
tt0874853
tt0818122
tt0111517
tt0162461
tt8151756
tt2797762
tt0018606
tt2666142
tt0040382
tt1073127
tt1139794
tt0302071
tt0271401
tt0103259
tt0398937
tt0399458
tt0163809
tt0810776
tt7491656
tt0067574
tt0486087
tt0038551
tt1921110
tt0225190
tt9759714
tt5329226
tt7462644
tt3981690
tt2273318
tt2274618
tt4318476
tt5956692
tt1101049
tt1175247
tt1179430
tt1195465
tt1326780
tt1414129
tt1419449
tt1458497
tt1641827
tt1498185
tt1512232
tt1545968
tt1073509
tt0995849
tt1046177
tt0870160
tt2274624
tt2291306
tt2291320
tt2388222
tt2738254
tt2099656
tt2100410
tt2101329
tt2179113
tt2226268
tt2244739
tt1964575
tt1972626
tt1772358
tt1815618
tt1838470
tt0273713
tt0274385
tt0121569
tt0455031
tt0469801
tt0473869
tt0427104
tt0317168
tt0005283
tt0057335
tt6187934
tt6188006
tt6477568
tt6731470
tt4239810
tt5337414
tt5494440
tt5581048
tt5588006
tt5597130
tt5657718
tt5735212
tt5781618
tt5088306
tt5787494
tt8242926
tt7658610
tt7738160
tt8976182
tt9407706
tt9680132
tt9698056
tt11122302
tt4356360
tt4422576
tt4427856
tt4440238
tt4703112
tt4769072
tt4786288
tt4827526
tt4860920
tt4902884
tt5088306
tt5119696
tt5149552
tt5190794
tt5206542
tt5210986
tt5247038
tt5257354
tt4015998

## Part 2:
<h5>(a) Install and run SQL on your machine. Use some GUI to see/test that it runs.</h5><br>
MySQL already installed in the desktop as it was mandatory for Data Management Class last quarter
<h5>(b) What data types would you choose to store "imdb_id", "title", and "year" in? Why?</h5><br>
As imdb id is alphanumeric in nature and is 9 character long. We will keep it as VARCHAR(20) to be safe<br>
title is a string so we can have it as a VARCHAR but since it's length can vary a lot. Its better to take a wide range to avoid concatenated names in our database. -> VARCHAR(200)<br>
Year will always be discrete (not continuous) and we can have it as an integer -> INT
<h5>(c) Do we need to create an additional column as a primary key to uniquely identify rows? If so, what column (type) do you propose? If not, which existing column can we use?</h5><br>
We generally use <column_name> NOT NULL PRIMARY KEY OR AUTO_INCREMENT NOT NULL to create a primary key<br>But in our case, we have imdb ID which is unique for each title, we can use it in our case
<h5>(d) Write a small program in Python or Java that <br>(i) connects to your local SQL instance (MySQL, MariaDB, and SQLite are the only acceptable versions. Choose either at your convenience. Use user "root" and NO passwords),<br> </h5>

In [97]:
#Connecting to MySQL using Python connector
import mysql.connector

#establishing the connection
#Adding an exception block to know connection status

try:
  conn = conn = mysql.connector.connect(
   user='root', password='2a57M98*', host='localhost'
)
except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
else:
   if (conn.is_connected()):
        print("Connected")

Connected

<h5>(ii) creates a database named "ucdavis"<br></h5>

In [99]:
#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Executing cursor with execute method and pass SQL query
cursor.execute("CREATE DATABASE ucdavis")
#Get list of all databases to check
cursor.execute("SHOW DATABASES")
#print all databases
for db in cursor:
    print(db)

('accountspayable',)
('avidreader',)
('bowlingleagueexample',)
('colonial',)
('entertainmentagencyexample',)
('information_schema',)
('mysql',)
('oact',)
('performance_schema',)
('pythondatabase',)
('recipesdatabase',)
('sakila',)
('salesordersdatabase',)
('sys',)
('ucdavis',)
('world',)

<h5>(iii) creates the table "omdb_test" containing the columns "imdb_id", "title", and "year". This small code will create an empty table.</h5>

In [100]:
#Dropping OMDB_test table if already exists.
#cursor = conn.cursor()
cursor.execute("USE ucdavis")
cursor.execute("DROP TABLE IF EXISTS ucdavis.OMDB_test")

#Creating table as per requirement
sql ='''CREATE TABLE OMDB_test(
   imdb_id VARCHAR(20) UNIQUE NOT NULL ,
   title VARCHAR(200),
   year INT
)'''
cursor.execute(sql)

#Get database table'
cursor.execute("SHOW TABLES")
for table in cursor:
    print(table)

('omdb_test',)

In [101]:
#Closing the connection
cursor.close()
conn.close()

## Part 3: 
<h5>(a) Write a program in Python or Java that uses the OMDb API to lookup/search _your_ top 10 choices of movie titles and extract their imdbIDs. Print the movie titles along with their imdbID to the screen. (E.g., search for "Dangal" or "Wolf Warrior 2" and record the imdbID that corresponds to the exact movie you have in mind).</h5><br>

In [59]:
#importing necessary libraries
import requests as r
import json as js
top_movies=['Life of pi','Her','Orphan','The GodFather','Moonlight','Get out',
            'Age Of Adaline','Shawshank Redemption','Seven','The Curious Case Of Benjamin Button']

#creating an empty list to store movie IDs
mov_ID=[]
for i in range(len(top_movies)):
        url="http://omdbapi.com/?t="+top_movies[i]+"&apikey=ce1b31ce&type=movie"
        #Request to the server
        response = r.get(url)
        result=js.loads(response.text)
        print("Title:",result['Title'])
        print("IMDB ID:",result['imdbID'])
        mov_ID.append(result['imdbID']) 
        print("\n")

Title: Life of Pi
IMDB ID: tt0454876


Title: Her
IMDB ID: tt1798709


Title: Orphan
IMDB ID: tt1148204


Title: The Godfather
IMDB ID: tt0068646


Title: Moonlight
IMDB ID: tt4975722


Title: Get Out
IMDB ID: tt5052448


Title: The Age of Adaline
IMDB ID: tt1655441


Title: The Shawshank Redemption
IMDB ID: tt0111161


Title: Seven Samurai
IMDB ID: tt0047478


Title: The Curious Case of Benjamin Button
IMDB ID: tt0421715

<h5>(b) Augment the program you developed in (a) to look up the movie details using the imdbIDs you found (Use only the IDs, NOT titles) and print out the result to the screen. </h5><br>

In [60]:
import requests as r
import json as js

for i in range(len(mov_ID)):
        url="http://omdbapi.com/?i="+mov_ID[i]+"&apikey=ce1b31ce&type=movie"
        #Request to the server
        response = r.get(url)
        #Create a JSON object
        json_obj=response.json()
        #Use dumps to print results properly
        text = js.dumps(json_obj, sort_keys=True, indent=4)
        print(text)

{
    "Actors": "Suraj Sharma, Irrfan Khan, Ayush Tandon, Gautam Belur",
    "Awards": "Won 4 Oscars. Another 78 wins & 131 nominations.",
    "BoxOffice": "$103,500,000",
    "Country": "USA, Taiwan, UK, Canada",
    "DVD": "12 Mar 2013",
    "Director": "Ang Lee",
    "Genre": "Adventure, Drama, Fantasy",
    "Language": "Arabic, English, Tamil, French, Japanese, Hindi, Chinese",
    "Metascore": "79",
    "Plot": "A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNTg2OTY2ODg5OF5BMl5BanBnXkFtZTcwODM5MTYxOA@@._V1_SX300.jpg",
    "Production": "20th Century Fox",
    "Rated": "PG",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "7.9/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "87%"
        },
        {
            "Source": "Metacritic",
            "Value": "79/100"
        }
    ],
    "Released": "21 Nov 2012",
    "Response": "True",
    "Runtime": "127 min",
    "Title": "Life of Pi",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Yann Martel (novel), David Magee (screenplay)",
    "Year": "2012",
    "imdbID": "tt0454876",
    "imdbRating": "7.9",
    "imdbVotes": "551,704"
}
{
    "Actors": "Joaquin Phoenix, Lynn Adrianna, Lisa Renee Pitts, Gabe Gomez",
    "Awards": "Won 1 Oscar. Another 81 wins & 183 nominations.",
    "BoxOffice": "$17,901,029",
    "Country": "USA",
    "DVD": "13 May 2014",
    "Director": "Spike Jonze",
    "Genre": "Drama, Romance, Sci-Fi",
    "Language": "English",
    "Metascore": "90",
    "Plot": "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg",
    "Production": "Warner Bros. Pictures",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "8.0/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "94%"
        },
        {
            "Source": "Metacritic",
            "Value": "90/100"
        }
    ],
    "Released": "10 Jan 2014",
    "Response": "True",
    "Runtime": "126 min",
    "Title": "Her",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Spike Jonze",
    "Year": "2013",
    "imdbID": "tt1798709",
    "imdbRating": "8.0",
    "imdbVotes": "495,091"
}
{
    "Actors": "Vera Farmiga, Peter Sarsgaard, Isabelle Fuhrman, CCH Pounder",
    "Awards": "1 win & 7 nominations.",
    "BoxOffice": "$41,472,886",
    "Country": "USA, Canada, Germany",
    "DVD": "27 Oct 2009",
    "Director": "Jaume Collet-Serra",
    "Genre": "Horror, Mystery, Thriller",
    "Language": "English, American Sign Language, Estonian",
    "Metascore": "42",
    "Plot": "A husband and wife who recently lost their baby adopt a 9 year-old girl who is not nearly as innocent as she claims to be.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTBjMjY0ODEtZGVkMy00MjUyLTlkMjAtNDBmNzVjOTk0NzQyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    "Production": "Warner Bros. Pictures",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "6.9/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "56%"
        },
        {
            "Source": "Metacritic",
            "Value": "42/100"
        }
    ],
    "Released": "24 Jul 2009",
    "Response": "True",
    "Runtime": "123 min",
    "Title": "Orphan",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "David Leslie Johnson-McGoldrick (screenplay), Alex Mace (story)",
    "Year": "2009",
    "imdbID": "tt1148204",
    "imdbRating": "6.9",
    "imdbVotes": "181,280"
}
{
    "Actors": "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
    "Awards": "Won 3 Oscars. Another 26 wins & 30 nominations.",
    "BoxOffice": "N/A",
    "Country": "USA",
    "DVD": "09 Oct 2001",
    "Director": "Francis Ford Coppola",
    "Genre": "Crime, Drama",
    "Language": "English, Italian, Latin",
    "Metascore": "100",
    "Plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "Production": "Paramount Pictures",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "9.2/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "98%"
        },
        {
            "Source": "Metacritic",
            "Value": "100/100"
        }
    ],
    "Released": "24 Mar 1972",
    "Response": "True",
    "Runtime": "175 min",
    "Title": "The Godfather",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)",
    "Year": "1972",
    "imdbID": "tt0068646",
    "imdbRating": "9.2",
    "imdbVotes": "1,502,403"
}
{
    "Actors": "Mahershala Ali, Shariff Earp, Duan Sanderson, Alex R. Hibbert",
    "Awards": "Won 3 Oscars. Another 225 wins & 284 nominations.",
    "BoxOffice": "$27,850,910",
    "Country": "USA",
    "DVD": "28 Feb 2017",
    "Director": "Barry Jenkins",
    "Genre": "Drama",
    "Language": "English",
    "Metascore": "99",
    "Plot": "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg",
    "Production": "A24 Films",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "7.4/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "98%"
        },
        {
            "Source": "Metacritic",
            "Value": "99/100"
        }
    ],
    "Released": "18 Nov 2016",
    "Response": "True",
    "Runtime": "111 min",
    "Title": "Moonlight",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Barry Jenkins (screenplay by), Tarell Alvin McCraney (story by)",
    "Year": "2016",
    "imdbID": "tt4975722",
    "imdbRating": "7.4",
    "imdbVotes": "243,114"
}
{
    "Actors": "Daniel Kaluuya, Allison Williams, Catherine Keener, Bradley Whitford",
    "Awards": "Won 1 Oscar. Another 150 wins & 199 nominations.",
    "BoxOffice": "$175,428,355",
    "Country": "USA, Japan",
    "DVD": "23 May 2017",
    "Director": "Jordan Peele",
    "Genre": "Horror, Mystery, Thriller",
    "Language": "English",
    "Metascore": "84",
    "Plot": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg",
    "Production": "Universal Pictures",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "7.7/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "98%"
        },
        {
            "Source": "Metacritic",
            "Value": "84/100"
        }
    ],
    "Released": "24 Feb 2017",
    "Response": "True",
    "Runtime": "104 min",
    "Title": "Get Out",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Jordan Peele",
    "Year": "2017",
    "imdbID": "tt5052448",
    "imdbRating": "7.7",
    "imdbVotes": "437,103"
}
{
    "Actors": "Blake Lively, Michiel Huisman, Harrison Ford, Ellen Burstyn",
    "Awards": "1 win & 10 nominations.",
    "BoxOffice": "N/A",
    "Country": "USA, Canada",
    "DVD": "08 Sep 2015",
    "Director": "Lee Toland Krieger",
    "Genre": "Drama, Fantasy, Romance",
    "Language": "English, Portuguese, Italian",
    "Metascore": "51",
    "Plot": "A young woman, born at the turn of the 20th century, is rendered ageless after an accident. After many solitary years, she meets a man who complicates the eternal life she has settled into.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTAzMTQzMTA2MjheQTJeQWpwZ15BbWU4MDk2MTg2MzUx._V1_SX300.jpg",
    "Production": "Lionsgate",
    "Rated": "PG-13",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "7.2/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "56%"
        },
        {
            "Source": "Metacritic",
            "Value": "51/100"
        }
    ],
    "Released": "24 Apr 2015",
    "Response": "True",
    "Runtime": "112 min",
    "Title": "The Age of Adaline",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "J. Mills Goodloe (screenplay by), Salvador Paskowitz (screenplay by), J. Mills Goodloe (screenplay), J. Mills Goodloe (story by), Salvador Paskowitz (story by)",
    "Year": "2015",
    "imdbID": "tt1655441",
    "imdbRating": "7.2",
    "imdbVotes": "144,316"
}
{
    "Actors": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    "Awards": "Nominated for 7 Oscars. Another 21 wins & 35 nominations.",
    "BoxOffice": "N/A",
    "Country": "USA",
    "DVD": "27 Jan 1998",
    "Director": "Frank Darabont",
    "Genre": "Drama",
    "Language": "English",
    "Metascore": "80",
    "Plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "Production": "Columbia Pictures",
    "Rated": "R",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "9.3/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "90%"
        },
        {
            "Source": "Metacritic",
            "Value": "80/100"
        }
    ],
    "Released": "14 Oct 1994",
    "Response": "True",
    "Runtime": "142 min",
    "Title": "The Shawshank Redemption",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Stephen King (short story \"Rita Hayworth and Shawshank Redemption\"), Frank Darabont (screenplay)",
    "Year": "1994",
    "imdbID": "tt0111161",
    "imdbRating": "9.3",
    "imdbVotes": "2,177,949"
}
{
    "Actors": "Toshir\u00f4 Mifune, Takashi Shimura, Keiko Tsushima, Yukiko Shimazaki",
    "Awards": "Nominated for 2 Oscars. Another 5 wins & 6 nominations.",
    "BoxOffice": "N/A",
    "Country": "Japan",
    "DVD": "01 Mar 1999",
    "Director": "Akira Kurosawa",
    "Genre": "Action, Adventure, Drama",
    "Language": "Japanese",
    "Metascore": "98",
    "Plot": "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BODdlYjU1Y2MtMWUxMy00YjJjLTgyMWItNzgzZmZkNTYxNWFkXkEyXkFqcGdeQXVyMTAwMjU1MzA2._V1_SX300.jpg",
    "Production": "Columbia Pictures",
    "Rated": "Not Rated",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "8.6/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "100%"
        },
        {
            "Source": "Metacritic",
            "Value": "98/100"
        }
    ],
    "Released": "19 Nov 1956",
    "Response": "True",
    "Runtime": "207 min",
    "Title": "Seven Samurai",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Akira Kurosawa (screenplay), Shinobu Hashimoto (screenplay), Hideo Oguni (screenplay)",
    "Year": "1954",
    "imdbID": "tt0047478",
    "imdbRating": "8.6",
    "imdbVotes": "295,310"
}

{
    "Actors": "Cate Blanchett, Brad Pitt, Julia Ormond, Faune Chambers Watkins",
    "Awards": "Won 3 Oscars. Another 81 wins & 157 nominations.",
    "BoxOffice": "$127,490,802",
    "Country": "USA",
    "DVD": "05 May 2009",
    "Director": "David Fincher",
    "Genre": "Drama, Fantasy, Romance",
    "Language": "English, Russian, French",
    "Metascore": "70",
    "Plot": "Tells the story of Benjamin Button, a man who starts aging backwards with consequences.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNjQ0NTY2ODY2M15BMl5BanBnXkFtZTgwMjE4MzkxMDE@._V1_SX300.jpg",
    "Production": "Paramount",
    "Rated": "PG-13",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "7.8/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "71%"
        },
        {
            "Source": "Metacritic",
            "Value": "70/100"
        }
    ],
    "Released": "25 Dec 2008",
    "Response": "True",
    "Runtime": "166 min",
    "Title": "The Curious Case of Benjamin Button",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Eric Roth (screenplay), Eric Roth (story), Robin Swicord (story), F. Scott Fitzgerald (short story)",
    "Year": "2008",
    "imdbID": "tt0421715",
    "imdbRating": "7.8",
    "imdbVotes": "554,605"
}

<h5>(c) "Recycle" + augment your code from (2.d) to insert the following information of _your_ top 10 movie titles into a new SQL table named "omdb":<br>title, year, genre, director, imdb_rating, rotten_tomatoes, metacritic, plot, box_office.<br>
Please store all ratings (imdb_rating, rotten_tomatoes, metacritic) all as full integers representing percentages, i.e., 8.5/10 = 85, 80% = 80<br></h5><br>

In [61]:
#Connecting to MySQL using Python connector
import mysql.connector

#establishing the connection
#entering the database names as ucdavis is itsn't there it gets created automatically
conn = mysql.connector.connect(
   user='root', password='', host='localhost', database='ucdavis'
)

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

#Dropping OMDB_test table if already exists.
cursor.execute("DROP TABLE IF EXISTS ucdavis.OMDB")

#Creating table as per requirement
sql ='''CREATE TABLE OMDB(
   imdb_id VARCHAR(20) PRIMARY KEY NOT NULL ,
   title VARCHAR(600),
   year INT(4),
   genre VARCHAR(255), 
   director VARCHAR(255), 
   imdb_rating INT(2), 
   rotten_tomatoes INT(2), 
   metacritic INT(2), 
   plot VARCHAR(1000), 
   box_office VARCHAR(20)
)'''
cursor.execute(sql)

#Checking where the cursor is at
for table in cursor:
    print(table)

In [62]:
print(cursor)

CMySQLCursor: CREATE TABLE OMDB(
   imdb_id VARCHAR(20..

In [63]:
#for each movie in the list mov_ID getting the data from api and inserting into the sql table omdb
for movie in mov_ID:
    url = "http://www.omdbapi.com/?apikey=ce1b31ce&i="+movie+"&type=movie"
    
    #Request to the server to get data
    response = r.get(url)
    my_mov=response.json()
 
    #converting ratings into integers
    imdb_rating=float((my_mov['Ratings'][0]['Value']).split("/")[0])*10
    rottentomatoes_rating=float((my_mov['Ratings'][1]['Value']).split("%")[0])
    metacritic_rating=float((my_mov['Ratings'][2]['Value']).split("/")[0])
    
    #inserting into the table omdb
    sql_query = "INSERT INTO omdb(imdb_id,title,year,genre,director, imdb_rating, rotten_tomatoes, metacritic, plot, box_office) VALUES(%s, %s, %s, %s, %s, %s,%s, %s, %s, %s)"
    record=(movie,my_mov['Title'],my_mov['Year'],my_mov['Genre'],my_mov['Director'],
            imdb_rating,rottentomatoes_rating, metacritic_rating,
            my_mov['Plot'],my_mov['BoxOffice'])
    cursor.execute(sql_query,record)
    print("inserted")
    print("\n")

inserted


inserted


inserted


inserted


inserted


inserted


inserted


inserted


inserted


inserted

In [65]:
conn.commit()

#validating whether records were inserted
cursor.execute("select * from omdb")
records = cursor.fetchall()
print("Total number of rows in omdb is: ", cursor.rowcount)

Total number of rows in omdb is:  10

In [66]:
#Closing the connection
cursor.close()
conn.close()

In [102]:
#QC Table contents
records

[('tt0047478',
  'Seven Samurai',
  1954,
  'Action, Adventure, Drama',
  'Akira Kurosawa',
  86,
  100,
  98,
  'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.',
  'N/A'),
 ('tt0068646',
  'The Godfather',
  1972,
  'Crime, Drama',
  'Francis Ford Coppola',
  92,
  98,
  100,
  'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
  'N/A'),
 ('tt0111161',
  'The Shawshank Redemption',
  1994,
  'Drama',
  'Frank Darabont',
  93,
  90,
  80,
  'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
  'N/A'),
 ('tt0421715',
  'The Curious Case of Benjamin Button',
  2008,
  'Drama, Fantasy, Romance',
  'David Fincher',
  78,
  71,
  70,
  'Tells the story of Benjamin Button, a man who starts aging backwards with consequences.',
  '$127,490,802'),
 ('tt0454876',
  'Life of Pi',
  2012,
  'Adventure, Drama, Fantasy',
  'Ang Lee',
  79,
  87,
  79,
  'A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.',
  '$103,500,000'),
 ('tt1148204',
  'Orphan',
  2009,
  'Horror, Mystery, Thriller',
  'Jaume Collet-Serra',
  69,
  56,
  42,
  'A husband and wife who recently lost their baby adopt a 9 year-old girl who is not nearly as innocent as she claims to be.',
  '$41,472,886'),
 ('tt1655441',
  'The Age of Adaline',
  2015,
  'Drama, Fantasy, Romance',
  'Lee Toland Krieger',
  72,
  56,
  51,
  'A young woman, born at the turn of the 20th century, is rendered ageless after an accident. After many solitary years, she meets a man who complicates the eternal life she has settled into.',
  'N/A'),
 ('tt1798709',
  'Her',
  2013,
  'Drama, Romance, Sci-Fi',
  'Spike Jonze',
  80,
  94,
  90,
  'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
  '$17,901,029'),
 ('tt4975722',
  'Moonlight',
  2016,
  'Drama',
  'Barry Jenkins',
  74,
  98,
  99,
  'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.',
  '$27,850,910'),
 ('tt5052448',
  'Get Out',
  2017,
  'Horror, Mystery, Thriller',
  'Jordan Peele',
  77,
  98,
  84,
  "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
  '$175,428,355')]